version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ngcash
      - POSTGRES_DB=bank
    ports:
      - '6432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local